[project]
name = "fedapay_connector"
version = "1.3.1"
description = "Connecteur asynchrone pour les paiements FedaPay"
readme = "README.md"
license = { text = "AGPL-3.0-or-later" }
authors = [
    { name = "ASSOGBA Dayane", email = "assogbadayane197@gmail.com" }
]
maintainers = [
  { name = "ASSOGBA Dayane", email = "assogbadayane197@gmail.com" }
]

keywords = ["fedapay", "paiement", "asynchrone", "API", "connector"]
classifiers = [
    "Intended Audience :: Developers",
    "License :: OSI Approved :: GNU Affero General Public License v3 or later (AGPLv3+)",
    "Programming Language :: Python :: 3",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Operating System :: OS Independent",
]
dependencies = [
    "pydantic[email]>=2.0",
    "aiohttp>=3.11.16",
    "fastapi>=0.115.12",
    "uvicorn>=0.34.2",
    "SQLAlchemy==2.0.41",

]
requires-python = ">=3.9"

license-files = ["LICEN[CS]E*"]

[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[project.urls]
Homepage = "https://github.com/Dasero197/fedapay_connector"
Issues = "https://github.com/Dasero197/fedapay_connector/issues"

[project.optional-dependencies]
docs = [
    "sphinx>=7.0.0",
    "furo>=2024.1.29",
    "myst-parser>=2.0.0",
    "sphinx-autodoc-typehints>=1.25.2",
]